---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-deploy 
  labels:
    app: facebook
    env: lab 

spec:
  selector:
    matchLabels:
      app: facebook 
  replicas: 2  
  template:
    metadata:
      name: fb-pod 
      labels:
        app: facebook
        env: lab
        tier: frontend 
        version: v1_AC
    spec:
      containers:
        - name: fb-pod-cont
          image: sravani2310/mcapp:latest
          ports:
            - containerPort: 8080
